roles:
  - name: community.docker
    src: https://github.com/ansible-collections/community.docker
    version: 3.10.2

collections:
  - name: infisical.vault
    version: 1.1.0
  - name: community.general
    version: 9.5.0
